// src/views/Help.vue
<template>
  <div class="relative flex min-h-screen flex-col bg-[#111518] overflow-x-hidden" style="font-family: Inter, 'Noto Sans', sans-serif;">
    <div class="layout-container flex h-full grow flex-col">
      <header class="flex items-center justify-between whitespace-nowrap border-b border-solid border-b-[#283139] px-10 py-3">
        <div class="flex items-center gap-4 text-white">
          <div class="size-4">
            <svg viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M24 18.4228L42 11.475V34.3663C42 34.7796 41.7457 35.1504 41.3601 35.2992L24 42V18.4228Z" fill="currentColor" />
              <path fill-rule="evenodd" clip-rule="evenodd" d="M24 8.18819L33.4123 11.574L24 15.2071L14.5877 11.574L24 8.18819ZM9 15.8487L21 20.4805V37.6263L9 32.9945V15.8487ZM27 37.6263V20.4805L39 15.8487V32.9945L27 37.6263ZM25.354 2.29885C24.4788 1.98402 23.5212 1.98402 22.646 2.29885L4.98454 8.65208C3.7939 9.08038 3 10.2097 3 11.475V34.3663C3 36.0196 4.01719 37.5026 5.55962 38.098L22.9197 44.7987C23.6149 45.0671 24.3851 45.0671 25.0803 44.7987L42.4404 38.098C43.9828 37.5026 45 36.0196 45 34.3663V11.475C45 10.2097 44.2061 9.08038 43.0155 8.65208L25.354 2.29885Z" fill="currentColor" />
            </svg>
          </div>
          <h2 class="text-white text-lg font-bold leading-tight tracking-[-0.015em]">DataLabeler</h2>
        </div>
        <div class="flex flex-1 justify-end gap-8">
          <div class="flex items-center gap-9">
            <router-link class="text-white text-sm font-medium leading-normal" :to="{name:'home'}">Overview</router-link>
            <router-link class="text-white text-sm font-medium leading-normal" :to="{name:'timeline'}">Features</router-link>
            <router-link class="text-white text-sm font-medium leading-normal" :to="{name:'help'}">Help</router-link>
            <router-link class="text-white text-sm font-medium leading-normal" :to="{name:'license'}">License</router-link>
          </div>
          <button class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#0b80ee] text-white text-sm font-bold leading-normal tracking-[0.015em]" @click="upload">
            <span class="truncate">Upload Data</span>
          </button>
        </div>
      </header>
      <div class="px-40 flex flex-1 justify-center py-5">
        <div class="layout-content-container flex flex-col max-w-[960px] flex-1 text-white">
          <div class="flex flex-col gap-4 px-4 py-10">
            <h1 class="text-2xl font-bold">Help with TRAINSET</h1>
            <h2 class="text-lg font-semibold">Input data format</h2>
            <p class="text-[#9cabba]">TRAINSET only accepts specific file formats. This <a class="underline" href="https://raw.githubusercontent.com/Geocene/trainset/master/sample_trainset.csv" target="_blank">sample CSV</a> is formatted correctly. Files uploaded to TRAINSET must have four comma-delimited columns with the header: <code>series, timestamp, value, label</code>; <code>null</code> data are not allowed.</p>
            <ul class="list-disc list-inside text-[#9cabba]">
              <li><code>series</code> is a unique name of the time series you are labeling.</li>
              <li><code>timestamp</code> is in <a href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank" class="underline">ISO 8601 format</a>.</li>
              <li><code>value</code> is a numeric scalar.</li>
              <li><code>label</code> is an integer representation of a boolean; <code>0==FALSE</code> and <code>1==TRUE</code>.</li>
            </ul>
            <h2 class="text-lg font-semibold pt-4">Labeling and Navigating</h2>
            <p class="text-[#9cabba]">Labels can be toggled by clicking on points or brushed across many points. Use the context bar or keyboard shortcuts to navigate your data.</p>
            <h2 class="text-lg font-semibold pt-4">Exporting</h2>
            <p class="text-[#9cabba]">After labeling, export a CSV with the <code>-labeled</code> suffix.</p>
            <h2 class="text-lg font-semibold pt-4">Privacy</h2>
            <p class="text-[#9cabba] mb-4">TRAINSET runs entirely client-side. Your data never leaves your browser. See the <a href="https://github.com/Geocene/trainset" target="_blank" class="underline">GitHub README</a> for details.</p>
          </div>
          <p class="text-[#9cabba] text-base font-normal leading-normal text-center mt-6">This project is a fork of <a href="https://github.com/Geocene/trainset" class="underline" target="_blank">TRAINSET</a>.</p>
        </div>
      </div>
    </div>
    <input type="file" id="upload-file" ref="fileInput" class="hidden" @change="fileCheck" />
  </div>
</template>

<script>
const { DateTime } = require('luxon');
export default {
  name: 'help',
  data(){ return { errorUpload:false }; },
  methods:{
    error(){
      this.errorUpload=true;
      this.$router.push({ name:'labeler', params:{ csvData:[], minMax:[], filename:'', headerStr:'', isValid:false } });
    },
    upload(){ this.$refs.fileInput.click(); },
    fileCheck(){
      window.onerror=(m,u,l)=>{ this.error(); };
      const fileInput=document.getElementById('upload-file').files.item(0);
      const filename=fileInput.name.split('.csv')[0];
      const reader=new FileReader();
      const seriesList=new Set();
      const labelList=new Set();
      const plotDict=[];
      let headerStr;
      reader.readAsText(fileInput);
      reader.onloadend=()=>{
        headerStr=reader.result.split(/\r?\n/)[0];
        const parseCsv=require('@/utils/parseCsv');
        const parsed=parseCsv(reader.result);
        parsed.forEach((row,idx)=>{
          const date=DateTime.fromJSDate(row.timestamp);
          seriesList.add(row.series);
          if(row.label) labelList.add(row.label);
          plotDict.push({id:idx.toString(),val:row.value.toString(),time:date,series:row.series,label:row.label});
        });
        if(!this.errorUpload){
          this.$router.push({ name:'labeler', params:{ csvData:plotDict, filename:filename, headerStr:headerStr, seriesList:Array.from(seriesList), labelList:Array.from(labelList), isValid:true } });
        }
      };
    }
  }
};
</script>

<style scoped>
</style>

// frontend/src/components/Help.tsx
import React from 'react';

const Help = () => {
  return (
    <div className="container">
      <div className="info">
        <h3 className="mb-5 title">Help with TRAINSET</h3>
        <h5 className="text-uppercase text-left subh">Input data format</h5>
        <p className='text-left'>TRAINSET only accepts specific file formats. This <a href="/static/files/sample_trainset.csv" download>sample CSV</a> is formatted correctly. Files uploaded to TRAINSET must have four comma-delimited columns with the header: <code>series, timestamp, value, label</code>; <code>null</code> data are not allowed.</p>

        <div className='text-left'>
          <ul style="list-style-type:square;">
            <li><code>series</code> is a unique name of the time series you are labeling. You can include multiple <code>series</code> in a CSV.</li>
            <li><code>timestamp</code> is a timestamp with time zone in <a href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO8601 format</a>. For example <code>2019-03-13T21:11:29+00:00</code> or <code>2019-03-13T21:11:29Z</code>.</li>
            <li><code>value</code> is a numeric scalar. Any real number is a valid for <code>value</code>.</li>
            <li><code>label</code> is an integer representation of a boolean; <code>0==FALSE</code> and <code>1==TRUE</code>. It is possible to upload data to TRAINSET that is pre-labeled (i.e. the <code>label</code> column does not have to start with all zeros). See the <a href="/static/files/sample_trainset.csv" download>sample CSV</a>.</li>
          </ul>
        </div>
        <p className="mb-5"><strong>Failure to properly format your data will result in failed uploads.</strong></p>

        <h5 className="text-uppercase text-left subh">Labeling and Navigating</h5>
        <p className='text-left mb-5'>Labeling is the act of applying labels, whether true or false, to your time series data. Labels can be toggled by clicking on points, or many labels can be applied at once by "brushing" (clicking and dragging) over many points. Navigation of the time series is accomplished either with shortcut keys or by highlighting a "focus region" on the "context bar" underneath the plot. The focus region can be brushed onto the context bar, dragged, and resized with the mouse or with shortcut keys. A legend of available shortcut keys is shown below the plot to help you navigate the time series and apply labels.</p>

        <h5 className="text-left text-uppercase subh">Exporting</h5>
        <p className='text-left mb-5'>After you finish labeling, you can export your data. An export will download a CSV to your default downloads folder. The name of this CSV will have the suffix <code>-labeled</code>. If the file you uploaded already had the suffix <code>-labeled</code>, no additional suffix will be added.</p>

        <h5 className="text-left text-uppercase subh">Privacy</h5>
        <p className='text-left mb-5'>TRAINSET is a client-side application. Although we use the word "upload" to describe importing data into TRAINSET, your time series data and labels are never transferred over the internet or visible to Geocene. Feel free to deploy TRAINSET locally using the instructions in the <a href="https://github.com/geocene/trainset" target="_blank">GitHub ReadMe</a>.</p>
      </div>
    </div>
  );
};

export default Help;
